# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Buildx'
description: 'GitHub Action to set up Docker Buildx'
author: 'crazy-max'
branding:
  color: 'blue'
  icon: 'truck'

inputs:
  buildx-version:
    deprecationMessage: 'This action is ARCHIVED and will not receive any updates, update your workflows to use the official Docker action docker/setup-buildx-action@v1'
    description: 'Buildx version. Example: v0.3.0'
    default: 'latest'
    required: false
  qemu-version:
    deprecationMessage: 'This action is ARCHIVED and will not receive any updates, update your workflows to use the official Docker action docker/setup-buildx-action@v1'
    description: 'QEMU static binaries Docker image version. Example: 4.2.0-7'
    default: 'latest'
    required: false

outputs:
  platforms:
    description: 'Available platforms (comma separated)'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
